### ISSUE TITLE
Update datasets in fitFfm_vignette_04_09.Rnw

### ISSUE THREAD

**Issue by JustinMShea** [braverock/FactorAnalytics#17]
Uses old `Stocks.df` file. Need to replace with `stocksCRSP` and `scoreSPGMI`.  

- fitFfm_vignette_04_09.Rnw

**Comment by martinrd3D** [comment]
Draft comment.  Willl fix this a little later

**Comment by martinrd3D** [comment]
I enter this comment because github "Flagged" my account with no reason, and I have not yet had a response from github, and want to see how being "Flagged" effects my ability to participate here.

**Comment by martinrd3D** [comment]
OK, the comment I just entered was labeled as "Spammy" with the text:  "This user is Spammy.  Their comments will only show in staff mode."

**Comment by martinrd3D** [comment]
Since we are not going to include the Sangeetha fitFfm vignette, both it and the data set Stocks.df should be put in the sandbox (in case we want to use it at some future date).
Then I will delete related examples in a few manual pages, after which this issue can be closed.

**Comment by JustinMShea** [comment]
Ok great. I will close this issue now, as we have another issue open for `Stocks.df`
