### ISSUE TITLE
-R CMD Check errors for datasets "wtsStocks145GmvLo.rda"

### ISSUE THREAD

**Issue by JustinMShea** [braverock/FactorAnalytics#26]
Running `grep -rnw wtsStocks145GmvLo R/*.R` returns the following files. 

R/datasets.R:133:#' @name wtsStocks145GmvLo
R/datasets.R:139:#' @usage data("wtsStocks145GmvLo")
R/portEsDecomp.R:84:#' data("wtsStocks145GmvLo")
R/portEsDecomp.R:85:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/portEsDecomp.R:96:#' portEsDecomp(fit.cross, weights = wtsStocks145GmvLo)  
R/portSdDecomp.R:78:#' data("wtsStocks145GmvLo")
R/portSdDecomp.R:79:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/portSdDecomp.R:90:#' portSdDecomp(fit.cross, wtsStocks145GmvLo)               
R/portVaRDecomp.R:85:#' data("wtsStocks145GmvLo")
R/portVaRDecomp.R:86:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/portVaRDecomp.R:97:#' portVaRDecomp(fit.cross, weights = wtsStocks145GmvLo)               
R/portVolDecomp.R:50:#' data("wtsStocks145GmvLo")
R/portVolDecomp.R:51:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/repExposures.R:48:#' data("wtsStocks145GmvLo")
R/repExposures.R:49:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/repExposures.R:57:#' repExposures(fit.cross, wtsStocks145GmvLo, isPlot = FALSE, digits = 4)
R/repExposures.R:58:#' repExposures(fit.cross, wtsStocks145GmvLo, isPrint = FALSE, isPlot = TRUE, 
R/repExposures.R:60:#' repExposures(fit.cross, wtsStocks145GmvLo, isPlot = TRUE, which = 1,
R/repExposures.R:62:#' repExposures(fit.cross, wtsStocks145GmvLo, isPrint = FALSE, isPlot = TRUE, 
R/repReturn.R:46:#' data("wtsStocks145GmvLo")
R/repReturn.R:47:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)                         
R/repReturn.R:56:#' repReturn(fit.cross, wtsStocks145GmvLo, isPlot = FALSE, digits = 4)
R/repReturn.R:57:#' repReturn(fit.cross, wtsStocks145GmvLo, isPrint = FALSE, isPlot = TRUE, 
R/repReturn.R:59:#' repReturn(fit.cross, wtsStocks145GmvLo, isPrint = FALSE, isPlot = TRUE, 
R/repReturn.R:61:#' repReturn(fit.cross, wtsStocks145GmvLo, isPrint = FALSE, isPlot = TRUE, 
R/repRisk.R:88:#' data("wtsStocks145GmvLo")
R/repRisk.R:89:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/repRisk.R:99:#' repRisk(fit.cross, wtsStocks145GmvLo, risk = "Sd", decomp = 'FPCR', 
R/repRisk.R:102:#' repRisk(fit.cross, wtsStocks145GmvLo, risk = c("VaR", "ES"), decomp = 'FPCR', 
R/repRisk.R:105:#' repRisk(fit.cross, wtsStocks145GmvLo, risk = "Sd", decomp = 'FPCR', 
R/riskDecomp.R:77:#' data("wtsStocks145GmvLo")
R/riskDecomp.R:78:#' wtsStocks145GmvLo = round(wtsStocks145GmvLo,5)  
R/riskDecomp.R:88:#' portES.decomp = riskDecomp(fit.cross, weights = wtsStocks145GmvLo, risk = "ES", portDecomp = TRUE)

**Comment by martinrd3D** [comment]
I am now thinking that if we should create a new GmvLO weight vector based on the smaller number of stocks for a smaller time window data set stocks30Scores3 (or similar) to be created, and included the weight vector in the FA data folder.
