### ISSUE TITLE
-R CMD Check errors for datasets "managers.rda"

### ISSUE THREAD

**Issue by JustinMShea** [braverock/FactorAnalytics#27]
Running `grep -rnw managers R/*.R` returns the following

R/cusumActMgr.R:9:#' Assessing the performance of the active managers is hard because active returns (i.e. portfolio return - benchmark return) are noisy.
R/cusumActMgr.R:11:#' the standard deviation of active returns. Empirical studies of active managers across a wide range of asset classes suggest that an
R/cusumActMgr.R:14:#' inefficiencies sometimes appear in their place. Consequently, the majority of active managers deliver active returns and IR close to 0, and even
R/fitTsfm.control.R:168:#' data(managers)
R/fitTsfm.control.R:169:#' fit <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fitTsfm.control.R:170:#'                factor.names=colnames(managers[,(7:9)]), 
R/fitTsfm.control.R:171:#'                data=managers, variable.selection="subsets", 
R/fitTsfm.R:126:#' data(managers)
R/fitTsfm.R:127:#' colnames(managers) = gsub(" ",'.',colnames(managers))
R/fitTsfm.R:129:#' fit <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fitTsfm.R:130:#'                factor.names=colnames(managers[,(7:9)]), data=managers)
R/fitTsfm.R:141:#' fit.sub <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fitTsfm.R:142:#'                    factor.names=colnames(managers[,(7:9)]), 
R/fitTsfm.R:143:#'                    data=managers, variable.selection="subsets", 
R/fitTsfm.R:147:#' fit.lar <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fitTsfm.R:148:#'                    factor.names=colnames(managers[,(7:9)]), 
R/fitTsfm.R:149:#'                    rf.name="US.3m.TR", data=managers, 
R/fmCov.R:50:#' data(managers)
R/fmCov.R:51:#' fit <- fitTsfm(asset.names=colnames(managers[, (1:6)]), 
R/fmCov.R:52:#'                factor.names=c("EDHEC.LS.EQ","SP500.TR"), data=managers)                              
R/fmEsDecomp.R:67:#' data(managers)
R/fmEsDecomp.R:68:#' fit.macro <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fmEsDecomp.R:69:#'                      factor.names=colnames(managers[,(7:8)]), data=managers)
R/fmmcSemiParam.R:61:#' data(managers)
R/fmmcSemiParam.R:62:#' fit <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fmmcSemiParam.R:63:#'                factor.names=colnames(managers[,(7:9)]), data=managers)
R/fmmcSemiParam.R:67:#' fmmc.returns <- fmmcSemiParam(factor.ret=managers[,(7:9)], beta=fit$beta, 
R/fmmcSemiParam.R:73:#' rownames(resid.par) <- colnames(managers[,(1:6)])
R/fmmcSemiParam.R:74:#' fmmc.returns.CF <- fmmcSemiParam(factor.ret=managers[,(7:9)], beta=fit$beta, 
R/fmmcSemiParam.R:81:#' rownames(resid.par) <- colnames(managers[,(1:6)])
R/fmmcSemiParam.R:82:#' fmmc.returns.skewt <- fmmcSemiParam(factor.ret=managers[,(7:9)], 
R/fmSdDecomp.R:58:#' data(managers)
R/fmSdDecomp.R:59:#' fit.macro <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fmSdDecomp.R:60:#'                      factor.names=colnames(managers[,(7:9)]),
R/fmSdDecomp.R:61:#'                      rf.name="US.3m.TR", data=managers)
R/fmVaRDecomp.R:66:#' data(managers)
R/fmVaRDecomp.R:67:#' fit.macro <- fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/fmVaRDecomp.R:68:#'                      factor.names=colnames(managers[,(7:8)]), data=managers)
R/portEsDecomp.R:62:#' data(managers)
R/portEsDecomp.R:63:#' fit.macro <- FactorAnalytics::fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/portEsDecomp.R:64:#'                      factor.names=colnames(managers[,(7:9)]),
R/portEsDecomp.R:65:#'                      rf.name=colnames(managers[,10]), data=managers)
R/portEsDecomp.R:73:#' names(wts) <- colnames(managers)[1:6]
R/portSdDecomp.R:56:#' data(managers)
R/portSdDecomp.R:57:#' fit.macro <- FactorAnalytics::fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/portSdDecomp.R:58:#'                      factor.names=colnames(managers[,(7:9)]),
R/portSdDecomp.R:59:#'                      rf.name=colnames(managers[,10]), data=managers)
R/portSdDecomp.R:67:#' names(wts) <- colnames(managers)[1:6]
R/portVaRDecomp.R:62:#' data(managers)
R/portVaRDecomp.R:63:#' fit.macro <- FactorAnalytics::fitTsfm(asset.names=colnames(manager[,(1:6)]),
R/portVaRDecomp.R:64:#'                      factor.names=colnames(managers[,(7:9)]),
R/portVaRDecomp.R:65:#'                      rf.name=colnames(managers[,10]), data=manager)
R/portVaRDecomp.R:73:#' names(wts) <- colnames(managers)[1:6]
R/portVolDecomp.R:35:#' data(managers)
R/portVolDecomp.R:36:#' fit.macro <- FactorAnalytics::fitTsfm(asset.names=colnames(manager[,(1:6)]),
R/portVolDecomp.R:37:#'                      factor.names=colnames(managers[,(7:9)]),
R/portVolDecomp.R:38:#'                      rf.name=colnames(managers[,10]), data=manager)
R/repRisk.R:68:#' data(managers)
R/repRisk.R:69:#' fit.macro <- FactorAnalytics::fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/repRisk.R:70:#'                      factor.names=colnames(managers[,(7:9)]),
R/repRisk.R:71:#'                      rf.name=colnames(managers[,10]), data=managers)
R/riskDecomp.R:52:#' data(managers)
R/riskDecomp.R:53:#' fit.macro <- FactorAnalytics::fitTsfm(asset.names=colnames(managers[,(1:6)]),
R/riskDecomp.R:54:#'                      factor.names=colnames(managers[,(7:9)]),
R/riskDecomp.R:55:#'                      rf.name=colnames(managers[,10]), data=managers)
R/riskDecomp.R:64:#' names(wts) <- colnames(managers)[1:6]

**Comment by braverock** [comment]
I think for all these `managers` examples, rather than 

`data(managers)`

it should be 

`data('managers', package='PerformanceAnalytics')`

**Comment by martinrd3D** [comment]
Of course.  And the code line needs to be changed accordingly in all man page examples, and in any vignettes that use the managers data.  I think this has already been taken care of in Sangeetha's fitTsfm vignette.

**Comment by JustinMShea** [comment]
Package builds without the "errors for datasets "managers.rda". 

used the below shell script to recursively find all instances of 
`data(managers)` 
in the `R/` function directory and replace with 
`data(managers, package = 'PerformanceAnalytics')` 

`grep -rl "data(managers)" R/*.R | xargs sed -i "s/data(managers)/data(managers, package = 'PerformanceAnalytics')/g"`

**Comment by JustinMShea** [comment]
Running `grep -rnw 'data(managers)' R/*.rR/fitTsfmMT.r:75:#' data(managers)` with a small ".r" reveals the following

R/fitTsfmUpDn.r:81:#' data(managers)
R/paFm.r:37:#' data(managers)
R/plot.pafm.r:30:#' data(managers)
R/plot.tsfm.r:122:#' data(managers)
R/plot.tsfmUpDn.r:38:#'  data(managers)
R/predict.tsfm.r:25:#' data(managers)
R/predict.tsfmUpDn.r:21:#' data(managers)
R/print.pafm.r:13:#'  data(managers)
R/print.tsfm.r:17:#' data(managers)
R/print.tsfmUpDn.r:17:#' data(managers)
R/summary.pafm.r:14:#' data(managers)
R/summary.tsfm.r:46:#' data(managers)
R/summary.tsfmUpDn.r:36:#' data(managers)
