### ISSUE TITLE
Install failed by LazyData: true

### ISSUE THREAD

**Issue by dan9401** [braverock/FactorAnalytics#47]
@JustinMShea As the title, I had an install error when running `devtools::install_github("braverock/FactorAnalytics")`. (After the merge conflict  in #41 is resolved.)

```
* installing *source* package ‘FactorAnalytics’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file ‘StockReturns.rda’ has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package ‘FactorAnalytics’
```

Removing the `LazyData: true` in the DESCRIPTION allows the package to be installed, but I'm not sure if this will mess up the compression.

It's not really helpful, but a similar issue here for reference: carlanetto/M4comp2018#1.

**Comment by JustinMShea** [comment]
Hi @dan9401,

We recently added git large file storage which has created issues if one doesn't have it. See the readme section on this topic.

I'd suggest installing git lfs and then trying to install the package again.

Thanks

**Comment by dan9401** [comment]
The problem still seems to persist after git-lfs installed, it may be something not configured right in my system though. Rstudio seems to be using the correct git path, is devtools configured separately?

**Comment by braverock** [comment]
`Rtools` needs to be installed to build from source if you are on Windows, and then `remotes` and `devtools` need to be installed too to build from RStudio.  Rstudio can handle most of the config except for the Rtools part.  

check the data files, if they are tiny text files (just pointers) then you are just seeing the pointer files, and not the actual data files when you clone.

**Comment by dan9401** [comment]
I was testing on a Mac system, with `remotes` and `devtools` installed of course. 
But for the experiment, I tested the installation in an Windows environment as well. Still getting the same error with all the build tools and `git-lfs` installed.

**Comment by JustinMShea** [comment]
@dan9401 Try to reinstall the package from my most recent commit

`remotes::install_github("braverock/FactorAnalytics", ref = "9d9e22a78b899078cecaa7fc70af9f626ad7cf9b")`

**Comment by JustinMShea** [comment]
It looks like I'm able to replicate your error, but when I clone the repo direclty (not using remotes or devtools), I don't get the issue. We are fairly certain this has to do with git lfs, which we may need to remove. 

If we remove the LazyData = true, it will reduce compression efficiency, and create WARNINGS on build that we need to eliminate in order to get this on CRAN

**Comment by JustinMShea** [comment]
@dan9401 After considering further, git lfs is helpful for us, especially as a key part of this project is the data. 

I think you should open this issue under remotes or devtools, as you now have two examples to list. I would go open an issue there and create a reproducible example with git lfs.

For FactorAnalytics, ditch both, and just use git to clone the repo and build it locally.

**Comment by braverock** [comment]
@dan9401 thanks for reporting to the `remotes` team.

I'm going to reference the remotes issue here so that we can more easily track upstream progress towards the fix.

[r-lib/remotes/issues/637] contains a description of the issue in how `remotes` doesn't handle git-lfs
