### ISSUE TITLE
FitFfm(fit.method = "WLS") ERROR

### ISSUE THREAD

**Issue by JustinMShea** [braverock/FactorAnalytics#68]
From the R/portVolDecomp.R examples files, method "WLS" fails. All other methods work.

See https://github.com/braverock/FactorAnalytics/blob/master/R/portVolDecomp.R#L69-L75, which produces the following
```
Error in lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok, : 
NA/NaN/Inf in 'x'
```

**Comment by midoshammaa** [comment]
Done using a warning.
